### ISSUE TITLE
jsx classnames being made lower case 

### ISSUE THREAD

**Issue by tnrich** [prettydiff/prettydiff#259] opened 2016-01-30 17:56 UTC
This
`classnames('twistCircularButton secondary downloadTemplateButton', `
Goes to this: 
`classnames('twistcircularbutton secondary downloadtemplatebutton',`

Is there any way to turn it off?

**Comment by prettydiff** [comment] 2016-01-30 22:10
No that would be a bug and not a feature.  I am having trouble reproducing the problem though.  Would you be able to provide some additional code?

**Comment by prettydiff** [comment] 2016-03-02 11:31
Closing potential defect due to an inability to reproduce.

**Closed by prettydiff** 2016-03-02 11:31 UTC
Labels: Requested Additional Information
