### ISSUE TITLE
Uncaught DOMException: Failed to set the 'innerHTML' property for specific inputs

### ISSUE THREAD

**Issue by brijmohan-saini** [prettydiff/prettydiff#466] opened 2017-07-11 07:40 UTC
![error](https://user-images.githubusercontent.com/30068780/28056257-e9591f4c-6639-11e7-8d9a-b9eda720fe2d.PNG)

Hi
Getting attached error for below inputs..

Code Type: Plain Text
Auto detect default: Plain Text

diffBase:
```

	
!		let
!	
	
```
diffNew:
```


End-procedure Heading_print
```

**Comment by prettydiff** [comment] 2017-07-11 11:28
I am having trouble reproducing the error, but the error certainly is valid.  If you have the time you could help me fix this by following these steps:

1. Clone the repo to your local computer
2. Point the browser to the repository, something like `file:///Users/username/prettydiff/index.xhtml`
3. In a code editor open *api/dom.js* and go to line 3164.
4. Instead of assigning that complex string to an innerHTML property instead wrap it in console.log so that the computed string is output to the console.
5. Paste that console output into a comment here, but be sure to put three backticks, *```*, on a line above and below this pasted value.  The backticks are github markdown that displays the text as code with all characters and formatting preserved.

The actual problem is that Pretty Diff is producing corrupted HTML and sending it as output.  By configuring the tool to run as xhtml (XML mode) instead of regular HTML corruption generates errors.  This means we need to see exactly what is corrupted in the output so that we can know where to look to resolve the corruption.

If you would like I could help you debug this to completion so that you can submit a pull request that gets merged in.

**Comment by brijmohan-saini** [comment] 2017-07-11 13:31
Hi
Below is the html it is trying to assign to codereportbody 

```<p>Code type is set to <strong>auto</strong>. Presumed language is <em>unknown</em>.</p><p><strong>Execution time:</strong> <em>0.016 seconds</em></p><p><strong>Number of differences:</strong> <em>3</em> difference from <em>2</em> lines of code.</p><div class='diff'><div class='diff-left'><h3 class='texttitle'>base</h3><ol class='count'><li>1</li><li>2</li><li>3</li></ol><ol class="data" data-prettydiff-ignore="true"><li class="replace"></em><em>!		le<em></em>t&#10;</li><li class="delete">!&#10;</li><li class="equal">&#10;</li></ol></div><div class='diff-right'><h3 class='texttitle'>new</h3><ol class='count' style='cursor:w-resize'><li>1</li><li class="empty">&#10;</li><li>2</li></ol><ol class="data" data-prettydiff-ignore="true"><li class="replace"><em>End-</em>proce<em>dure Heading_prin</em>t&#10;</li><li class="empty"></li><li class="equal">&#10;</li></ol></div><p class="author">Diff view written by <a href="http://prettydiff.com/">Pretty Diff</a>.</p></div>```

**Comment by brijmohan-saini** [comment] 2017-07-11 13:37
em has no starting tag
![image](https://user-images.githubusercontent.com/30068780/28070917-1b77780c-666c-11e7-8b24-373cd5a1c7de.png)

**Comment by prettydiff** [comment] 2017-07-11 14:53
Excellent debugging!  I am going to look and see why this could be.  It will be challenging for me to debug if I cannot reproduce the problem.  The problem code is lib/diffview.js

**Comment by prettydiff** [comment] 2017-07-11 15:21
I can reproduce the defect now.  I just had to edit your opening comment to ensure I was grabbing the code samples properly.  Somehow it is the difference in whitespace that allows this error.

**Comment by brijmohan-saini** [comment] 2017-07-12 04:59
Hello, Good Morning!

One more case where removing any of the character will make it work. This might make the debugging easier.

1. **Not Working;** Inputs- Base:**le** New:**!he**
Response: ```<p>Code type is set to <strong>auto</strong>. Presumed language is <em>unknown</em>.</p><p><strong>Execution time:</strong> <em>0.015 seconds</em></p><p><strong>Number of differences:</strong> <em>1</em> differences from <em>1</em> line of code.</p><div class='diff'><div class='diff-left'><h3 class='texttitle'>base</h3><ol class='count'><li>1</li><li>2</li></ol><ol class="data" data-prettydiff-ignore="true"><li class="replace"></em><em>le&#10;</li><li class="equal">&#10;</li></ol></div><div class='diff-right'><h3 class='texttitle'>new</h3><ol class='count' style='cursor:w-resize'><li>1</li><li>2</li></ol><ol class="data" data-prettydiff-ignore="true"><li class="replace"><em>!</em>he&#10;</li><li class="equal">&#10;</li></ol></div><p class="author">Diff view written by <a href="http://prettydiff.com/">Pretty Diff</a>.</p></div>```

2. **Working;** Inputs- Base:**l** New:**!he**
Response: ```<p>Code type is set to <strong>auto</strong>. Presumed language is <em>unknown</em>.</p><p><strong>Execution time:</strong> <em>0.001 seconds</em></p><p><strong>Number of differences:</strong> <em>1</em> differences from <em>1</em> line of code.</p><div class='diff'><div class='diff-left'><h3 class='texttitle'>base</h3><ol class='count'><li>1</li><li>2</li></ol><ol class="data" data-prettydiff-ignore="true"><li class="replace"><em>l</em>&#10;</li><li class="equal">&#10;</li></ol></div><div class='diff-right'><h3 class='texttitle'>new</h3><ol class='count' style='cursor:w-resize'><li>1</li><li>2</li></ol><ol class="data" data-prettydiff-ignore="true"><li class="replace"><em>!he</em>&#10;</li><li class="equal">&#10;</li></ol></div><p class="author">Diff view written by <a href="http://prettydiff.com/">Pretty Diff</a>.</p></div>```

3. **Working;** Inputs- Base:**le** New:**he**
```<p>Code type is set to <strong>auto</strong>. Presumed language is <em>unknown</em>.</p><p><strong>Execution time:</strong> <em>0 seconds</em></p><p><strong>Number of differences:</strong> <em>1</em> differences from <em>1</em> line of code.</p><div class='diff'><div class='diff-left'><h3 class='texttitle'>base</h3><ol class='count'><li>1</li><li>2</li></ol><ol class="data" data-prettydiff-ignore="true"><li class="replace"><em>l</em>e&#10;</li><li class="equal">&#10;</li></ol></div><div class='diff-right'><h3 class='texttitle'>new</h3><ol class='count' style='cursor:w-resize'><li>1</li><li>2</li></ol><ol class="data" data-prettydiff-ignore="true"><li class="replace"><em>h</em>e&#10;</li><li class="equal">&#10;</li></ol></div><p class="author">Diff view written by <a href="http://prettydiff.com/">Pretty Diff</a>.</p></div>```

![image](https://user-images.githubusercontent.com/30068780/28102276-d02bdbec-66eb-11e7-876b-15919a999d7f.png)

**Comment by prettydiff** [comment] 2017-07-12 18:50
I created a resolution at branch `#466`.  You did most of the work on this, so if you would like you can pull this code down and see if it cures the problem in all cases.  Then open a pull request and I will merge it to master.

**Comment by brijmohan-saini** [comment] 2017-07-14 10:40
Thank you. It solved the issue. One more suggestion: In code report, for longer lines there is no word break which makes it difficult to view the report. 
Currently I have used word-wrap:break-word and set the width for **li**  inside class **data** (.data li). But the height of fields don't match (refer Screenshot 1)

Workaround:
After the response is written to code report, I have in javascript compared heights of all fields in the same row and adjusted the height of all fields to the max height among them (refer Screenshot2). But this takes around 2 seconds for large number of rows (around 5000)

Question:
Is there any setting for dsiplaying report with words wrapped ?
If not, can you please look into this and suggest something because manipulating the response is taking a lot of time and it hangs for that duration.


Screenshot 1
![image](https://user-images.githubusercontent.com/30068780/28208843-61f19af4-68ad-11e7-8668-54ffa8924fb2.png)

Screenshot 2
![image](https://user-images.githubusercontent.com/30068780/28208462-5a817462-68ab-11e7-8f88-7886274baddf.png)

**Comment by prettydiff** [comment] 2017-07-14 11:11
That is an excellent point.  The word wrap is something I will likely address when I revise output formats in #454.  In the meantime you can horizontally drag and drop the line number column under "new".  I know this is a frustratingly painful approach, but it is better than nothing.

**Comment by prettydiff** [comment] 2017-07-14 11:12
Closing with pull request https://github.com/prettydiff/prettydiff/pull/468

**Closed by prettydiff** 2017-07-14 11:12 UTC
Labels: API, Defect, Underway
