### ISSUE TITLE
how can result of compare display as the html page instead of the html code?

### ISSUE THREAD

**Issue by RockyUs** [prettydiff/prettydiff#387] opened 2016-11-17 18:03 UTC
how can result of compare display as the html page instead of the html code, the difference identified as the different color, like as red word or different background color? thanks.

**Comment by prettydiff** [comment] 2016-11-17 20:23
This is a feature that has been requested numerous times and I have had no idea how to go about it.  Last month I thought of a solution.

My plan of attack is as follows:

* Replace the closing `</head>` tag with a small style tag block like: `<style type="text/css">my custom css code here</style></head>`
* Find elements that are different and adding a class name to them.
* If only text is different then wrap the difference in a span tag with a created class name.

That should mostly be it.  The difference would manifest visually when run in a browser using the CSS outline property as this doesn't occupy the box model.

**Comment by prettydiff** [comment] 2016-11-17 20:24
* https://github.com/prettydiff/prettydiff/issues/13
* https://github.com/prettydiff/prettydiff/issues/19

**Comment by prettydiff** [comment] 2018-08-13 09:05
I am closing this issue as a duplicate of #13 

This item is hidden behind option *diff_rendered_html* and is available for testing in the 3.0.0 branch.

**Closed by prettydiff** 2018-08-13 09:05 UTC
Labels: 3.0.0, Enhancement, Pending Release
