### ISSUE TITLE
Beautification erase code when it meets several Twig `if` statements in the same line 

### ISSUE THREAD

**Issue by developerlover** [prettydiff/prettydiff#510] opened 2018-03-06 12:58 UTC
# Description

Like title says, beautification erase code in lines that contains several Twig `if` statements. 

Seems like, from second `endif` tag beautification deletes everything after it, including the second `endif` tag.

# Input Before Beautification

This is what the code looked like before:

```
<a {% if foo %} target="_blank" {% endif %} {% if bar %} rel="nofollow" {% endif %}>foobar</a>
<a {% if foo %} target="_blank" {% endif %} {% if bar %} rel="nofollow" {% endif %} {% if bar %} rel="nofollow" {% endif %}>foobar</a>
```

# Expected Output

The beautified code should have looked like this:

```
<a {% if foo %} target="_blank" {% endif %} {% if bar %} rel="nofollow" {% endif %}>foobar</a>
<a {% if foo %} target="_blank" {% endif %} {% if bar %} rel="nofollow" {% endif %} {% if bar %} rel="nofollow" {% endif %}>foobar</a>
```

# Actual Output

The beautified code actually looked like this:

```
<a {% if foo %} target="_blank" {% endif %} {% if bar %} rel="nofollow">foobar</a>
<a {% if foo %} target="_blank" {% endif %} {% if bar %} rel="nofollow">foobar</a>
```

Thank you!
Pablo.

**Comment by prettydiff** [comment] 2018-03-07 21:36
Duplicate of #502

**Closed by prettydiff** 2018-03-07 21:36 UTC
Labels: Defect, Not started, Parsing
