### ISSUE TITLE
Various Liquid formatting issues

### ISSUE THREAD

**Issue by panoply** [prettydiff/prettydiff#605] opened 2019-06-17 03:02 UTC
Below are a list of issues I've encountered using PrettyDiff beautification with the Liquid language. I use PrettyDiff to handle formatting of Liquid / HTML syntax in a [vscode extension ](https://github.com/panoply/vscode-liquid) I maintain. 

### Case Blocks
PrettyDiff doesn't seem to understand Liquid case switch blocks.

**Additional Information**
 Liquid separates case expression using `{% when 'condition' %}` tags opposed to colons `:`

**Code Example**

Before:
```
{% case handle %}
  {% when 'cake' %}
     This is a cake
  {% when 'cookie' %}
     This is a cookie
  {% else %}
     This is not a cake nor a cookie
{% endcase %}
```
After: 
```
{% case handle %}{% when 'cake' %}
This is a cake{% when 'cookie' %}
This is a cookie{% else %}
This is not a cake nor a cookie
{% endcase %}
```
Expected:
```
{% case handle %}
  {% when 'cake' %}
     This is a cake
  {% when 'cookie' %}
     This is a cookie
  {% else %}
     This is not a cake nor a cookie
{% endcase %}
```

**Suggestion:**
Formatting of liquid case blocks to respect `case_space` and `no_case_indent` rules

### Comments
PrettyDiff has trouble formatting non whitespace (`{% comment %}`) and whitespace (`{%- comment -%} `) comment tag blocks. It seems the lexer treats both of these differently. 

**Additional Context**
Any Liquid tags that contain a dash `-` suffix on tags will have whitespace removed.  For example, `{%- tag_name -%}` removes whitespace whereas `{% tag_name %}` does not. 

**Code Example**

Before:
```
{% comment %}
hello world
{% endcomment %}

{%- comment -%}
hello world
{%- endcomment -%}
```

After:
```
{% comment %}hello world{% endcomment %}
{%- comment -%}
hello world

{%- endcomment -%}
```

Expected:
```
{% comment %}
    hello world
{% endcomment %}

{%- comment -%}
    hello world
{%- endcomment -%}
```

**Suggestion:** 
Formatting of liquid comment blocks to respect rules like `comment_line` and `comment`. 

### Prefixed colon `:` newline
Prettydiff will output text content on a newline if text is prefixed with a  colon (`:`) and space
. 
**Code Example**

Before:
```
{% capture foo_object %}
{% if condition %}
size:  {{ foo_bar  }},
color: {{ bar | json }}
{% endif %}
{% endcapture %}
```

After: 
```
{% capture foo %}
    {% if bar %}
        {
                size:
        {{ foo_bar }};
                color:
        {{ bar | json }}
        }
    {% endif %}
{% endcapture %}
```
**Additional Information**
It doesn't matter where the key value syntax resides, so even when not contained within capture or conditional blocks PrettyDiff will still implement a newline.  Take the following example:

Before:
```
test: {{ variable }}
```
After:
```
test: 
{{ variable }}
```
Importantly, a newline will not be generated if no space is used between the key and value pair, example:

Before:
```
test:{{ variable }}
```

After:
```
test:{{ variable }}
```

> When no space between the `:` and liquid tag is used, formatting will work as expected.

Expected:
```
{% capture foo_object %}
   {% if condition %}
      size:  {{ foo_bar  }},
      color: {{ bar | json }}
   {% endif %}
{% endcapture %}
```

<hr>

### Summary
I would love to be of more help in terms of contributions to resolve these issues but in all honesty I find navigating the PrettyDiff project quite difficult. If there is anything I can do to further assist though, please don't hesitate to ask.

**Comment by prettydiff** [comment] 2019-06-17 19:51
The first two defects are almost entirely defects in the parser: https://github.com/Unibeautify/sparser  The final defect is almost certainly a beautification only defect requiring unique rules.

Please feel free to voice any frustrations you encounter when examining the code or the project's organization.  There are probably lots of gaps or opportunities for improvement in documentation.

**Comment by panoply** [comment] 2019-06-23 17:41
@prettydiff Going over your commits in Sparser was a great help for me in terms of understanding the code base. I'll keep diving deeper into Sparser itself.

**Comment by prettydiff** [comment] 2019-06-23 19:05
Thank you so much for putting time into this.  If you have questions or encounter areas that really don't make sense please let me know.  Sparser and Pretty Diff execute in identical ways with similar architectures.  You can run the `node js/services server` command to test Sparser in the browser by going to http://localhost:9999/demo or by running `node js/services valid` to test the application against the test units.

The switch case defect at the top is proving to be quite a challenge for me.  I am trying to solve it with generalized structures that could apply to other languages that may have similar constructs.  I have to go back and fix something though, as I just discovered a regression.

The reason for the complexity around the switch/case block is that from the markup side I am treating it as a if/else group.

```javascript
if (a) {
    something;
} else if (b) {
    something_else;
} else {
    whatever;
}
```

The above code example is JavaScript, but if/else blocks follow the same structure in most markup and template schemes.  Notice that the if/else is a direct one-for-one chain of containment between the curly braces (or tags in the case of markup).  Switch/case is structurally different:

```javascript
switch (a) {
    case 1;
        something;
        break;
    case 2:
        something_else;
        break;
    default:
        whatever;
}
```

Notice that the case/default groups are wrapped in a parent.  The final item of the chain does not have its own closing syntax as it simply closes with the group's parent closing syntax.  Also these `case` keywords are structured similarly like `else` keywords, except the first one immediately follows the start syntax of the parent grouping.

In the various scripting languages I support using the *script* lexer this isn't a big deal, because everything uses the say keywords even if the languages are entirely unrelated.  In markup this isn't the case.  Various different tag names are used between different template schemes even when those various template schemes may share the same syntax, such as Liquid and Twig.  This is why I am trying to solve the problem from a structural/relational perspective instead of just using tag names.  Breaking common assumptions of language structures and generic relationships can be tricky.

**Comment by panoply** [comment] 2019-06-23 19:43
Thanks for the insight on this. I'm looking forward to becoming more fluent with this project over the summer. 

Regarding the switch case statement, because there is no `break;` in Liquid what about treating `{% else %}` as  `default`. In JavaScript (for example) the `break` keyword is optional and so is the `default` – If the parser was to encounter an `{% else %}` keyword within the `{% case %}` tag it would imply `default` even though in the liquid language it's a conditional execution keyword it's treated as default. 

I don't know the complications or adverse effects by doing this in terms of other the parser and different language structures, It's just a thought.

**Closed** 2019-06-24 00:36 UTC
Labels: Defect
