### ISSUE TITLE
jscorrect missing semicolons

### ISSUE THREAD

**Issue by thurt** [prettydiff/prettydiff#281] opened 2016-03-01 05:50 UTC
Hello--
I am having a small issue with missing semicolons--this relates to jscorrect http://prettydiff.com/guide/jscorrect.xhtml. 

When I put through `mode:'beautify' correct:true`, the missing semis seem be around (ES6 syntax) computed property names. I provide some context code if this helps. These are missing semis that caused definite syntax errors:
```javascript
app.add(myModel, {
          [myName + 'clear']() {
            if(myView.classList.contains('hidden')) {
              return;
            }
            myView
              .classList
              .add('hidden')myKey = null ////////////// HERE
          },
          [myName + 'set'](key) {
            myKey = key for (let name in myData) { ////////////// HERE
              myData[name].textContent = this.get(myKey, name);
            }
       // etc... 
```
```javascript
app.add(myModel, {
          [myToolbar + 'new']() {
            auto_open = true this.new() /////////// HERE
          },
          [myToolbar + 'delete']() {
            this.delete(myKeys.get(open_el))
          },
   // etc...
```
```javascript
        app.add(myModel, {
          [myName + 'enableButton'](btn_name) {
            var btn = myData[btn_name]if (btn !== undefined) { ///////////// HERE
              btn.disabled = false;
            } else {
              console.warn('Cannot find button by name', btn_name);
            }
          },
          [myName + 'disableButton'](btn_name) {
            var btn = myData[btn_name]if (btn !== undefined) { ///////////// HERE
              btn.disabled = true;
            } else {
              console.warn('Cannot find button by name', btn_name);
            }
          }
        });
```

**Comment by prettydiff** [comment] 2016-03-01 12:11
The problem is that I am incorrectly describing the containing structure.  I am calling the curly braces which precede the `var` key words as objects, which is clearly wrong.

I fixed the issue so that curly braces immediately following a closing parenthesis whose opening parenthesis is not immediately following a word a `block` instead of an `object`.  Since ES6 blocks can be labeled and referenced by that label they are practically no different than an anonymous function expression body (there is still a lot of difference in the spec) except these critters do not return a value.

I will publish the update in just a moment.

**Closed** 2016-03-01 12:24 UTC
Labels: Defect, Parsing, Underway

**Comment by prettydiff** [comment] 2016-03-01 12:25
Published as v1.16.24

**Comment by prettydiff** [comment] 2016-03-01 12:44
On second thought I will publish an amended fix later in the day.  These appear to be function bodies and the amended fix will describe those structures as functions.

**Comment by thurt** [comment] 2016-03-01 14:55
Hi-- I found MDN has a nice summary of the available syntax forms related to this issue:
```javascript
var obj = {
  property( parameters… ) {},
  *generator( parameters… ) {},
// also with computed keys:
  [property]( parameters… ) {},
  *[generator]( parameters… ) {},
// compare ES5 getter/setter syntax:
  get property() {},
  set property(value) {}
};
```
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions

**Comment by thurt** [comment] 2016-03-01 15:20
Confirmed e5eac45 fixes all missing semis described in my first post
Thank you much! prettydiff is a joy to work with
