### ISSUE TITLE
Inconsistent handling of whitespace between xml elements

### ISSUE THREAD

**Issue by murrayju** [prettydiff/prettydiff#110] opened 2015-06-22 18:23 UTC
Here is a gist containing 2 nearly identical xml files: https://gist.github.com/murrayju/d164df81989e0285c359

These only differ by 2 space characters, before and after the `<meta/>` element. For some reason, the formatter does not handle these the same, and inserts a newline + tabs in one, but not the other. This appears to be special treatment of the self-closing `<meta/>` tag, as other elements do not behave the same way.

This causes the diff tool to report differences, when there are none.

**Comment by prettydiff** [comment] 2015-06-22 20:15
This is intended behavior.

Typically in XML this difference is irrelevant. In HTML it is always relevant and it is relevant in the case where there is a text node in close proximity to the self-closing element. It is also always relevant in the case where a self-closing element is intended to supply some programmatic user content.  For example form controls are typically self-closing elements that are intended for human consumption directly and no differently than text.

A space between any two tags is a text node even if the textContent value of that node only contains white space.  Unless there is some presentation setting specifying otherwise white space is tokenized to a single space character, which is always communicated to the end user.  In the case where an XML file contains only data, particularly when that data is only used in some automation capacity, then this white space/text node distinction is irrelevant because end users will never read from the file.

Unfortunately, I cannot know in which cases communicating additional space characters to users is relevant from only analyzing code samples but I don't know which code samples will ever be consumed by users. As a result I have to take the most conservative (lowest risk) path available.

Fortunately, I did envision this scenario and created the option [force_indent](http://prettydiff.com/documentation.xhtml#force_indent) option.  Applying this option seemed to work for me. If you notice any problems please reopen this issue.

**Closed by prettydiff** 2015-06-22 20:15 UTC

**Comment by murrayju** [comment] 2015-06-22 20:48
Thanks for the info. Can confirm that the `force_indent` option alleviates the problem.

The unfortunate thing is that I'm having this problem due to differences in browser implementation. I'm using the browser's xslt engine, and the `<meta/>` tag is injected by the engine. Chrome injects it with surrounding whitespace, while Firefox outputs no whitespace at all :(
