### ISSUE TITLE
Liquid: space padding for dashes in variables

### ISSUE THREAD

**Issue by bgodin** [prettydiff/prettydiff#340] opened 2016-08-10 17:33 UTC
I'm seeing the following issue and have been unable to find a setting that fixes it:

**Input:**
` {% assign productsPerPage = settings.products-per-row | times: settings.rows-per-page %}`
**Output:**
`{% assign productsPerPage = settings.products - per - row | times : settings.rows - per - page %}`

The beautify breaks the code. Can you suggest a way to not insert spaces in the dashes? Is this a feature already implemented?

**Comment by prettydiff** [comment] 2016-08-10 19:39
This is fixed in the 2.1.3 branch and will merge to master soon.  The cause of the defect is a minor collision between TWIG and Liquid which both make use of `{%` delimiters

**Closed** 2016-08-14 17:13 UTC
Labels: Defect, Parsing, Pending Release
