### ISSUE TITLE
nodejs require, investigate a modules.exports from node-local.js

### ISSUE THREAD

**Issue by faiwer** [prettydiff/prettydiff#176] opened 2015-10-05 07:34 UTC
In documentation:
```js
var prettydiff = require("prettydiff"),
    args       = {
        source: "asdf",
        diff  : "asdd",
        lang  : "text"
    },
    output     = prettydiff.api(args);
```

But after 1.14.0 `prettydiff === {}`; In commit:
```js
global.safeSort      = require("../lib/safeSort.js").api;
global.csspretty     = require("../lib/csspretty.js").api;
global.csvpretty     = require("../lib/csvpretty.js").api;
global.diffview      = require("../lib/diffview.js").api;
global.jspretty      = require("../lib/jspretty.js").api;
global.markuppretty  = require("../lib/markuppretty.js").api;
global.jsxstatus     = global.jspretty.jsxstatus;
```
global? in nodejs? o_O... why???

**Comment by faiwer** [comment] 2015-10-05 07:35
In lodash (example): https://github.com/lodash/lodash/blob/master/lodash.js#L13101

**Comment by faiwer** [comment] 2015-10-05 07:45
Also in CLI after require('prettydiff')
![img_05_10_13 42 00_b1e6986271a](https://cloud.githubusercontent.com/assets/744114/10275150/f804e9f6-6b66-11e5-9652-f02064f47fd7.png)

https://github.com/prettydiff/prettydiff/blob/master/api/node-local.js#L2085

**Comment by prettydiff** [comment] 2015-10-05 12:26
The reason why I did this is to make each of the library files independent stand-alone modules.  I wanted to do this in a way that works uniformly in all environments and natively without a build process.  Eventually I am going to entirely retire and remove the `prettydiff.js` file.

The big difference between the lodash approach and what I had to do is:

* lodash is one file
* lodash does not reference itself via `define`

In Pretty Diff the modules `jspretty` and `markuppretty` request each other.  In Node this produces an infinite recursive loop.  A way to solve that problem is to define the module with a proper name then assign it to a namespace upon request (or rather require).  I chose the namespace `global` because it exists by default in Node.  I can create an empty object of the same name for execution on the web just to keep everything uniform and nothing undefined.

Now, let's figure out what the recent change is breaking in your code so that we can fix it.  The screenshot is what the `api/node-local.js` file generates by default if it gets no options.

**Comment by faiwer** [comment] 2015-10-05 12:42
May be make "wrapper" index file for nodeJS, with module.exports = %prettyjsnamespace%?

**Comment by prettydiff** [comment] 2015-10-05 13:09
That is actually a really good idea.  I am going to start investigating that tonight.

Did this update break your application though?

**Comment by Casedy** [comment] 2015-10-05 13:13
same problem in https://github.com/sprity/sprity

**Comment by prettydiff** [comment] 2015-10-05 15:00
@Casedy let me know if you are still have a problem with v1.14.2.

**Comment by Casedy** [comment] 2015-10-05 16:18
@prettydiff 
```
Error: Cannot find module 'lib/csspretty.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at glib_prettydiff (/node_modules/prettydiff/prettydiff.js:102:32)
    at Object.<anonymous> (/node_modules/sprity/node_modules/prettydiff/prettydiff.js:119:6)
```

**Comment by prettydiff** [comment] 2015-10-05 17:10
I can see where in sprity Pretty Diff is being used - https://github.com/sprity/sprity/blob/master/lib/style.js#L38-L53

I was able to reproduce the error by running this code on the command line:

    var Promise = require('bluebird');
    var prettydiff = require("prettydiff");
    var beautify = function (opt) {
      return Promise.method(function (style) {
        if (!opt.template && processor.isBeautifyable(opt)) {
          return prettydiff.api({
            source: style,
            lang: 'css',
            mode: 'beautify',
            inchar: opt['style-indent-char'] === 'space' ? ' ' : '\t',
            insize: opt['style-indent-size']
          })[0];
        }
        else {
          return style;
        }
      });
    };
    beautify();

With the change for v1.14.1 I am checking if process.cwd() returns root (which is the case in Atom) otherwise I am setting an empty string for variable that prefixes the module paths.  Instead of an empty string I need to set `"./"`.  I will have this pushed out very soon.

**Comment by prettydiff** [comment] 2015-10-05 17:51
@Casedy  Try now with version v1.14.3.

**Comment by Casedy** [comment] 2015-10-05 18:08
@prettydiff Now it works properly, thank you.

**Comment by prettydiff** [comment] 2015-10-05 18:12
@Casedy no, thank you for bringing this to my attention and being patient with me while I came to a solution.

**Closed** 2015-11-03 12:22 UTC
Labels: Enhancement, Not started
