### ISSUE TITLE
Javascript "Uncaught ReferenceError: global is not defined"

### ISSUE THREAD

**Issue by Pennicillina** [prettydiff/prettydiff#389] opened 2016-11-23 09:35 UTC
Hi, 

I'm tryin to use prettydiff to obtain adiff between two divs but at page load I get this error:

Uncaught ReferenceError: global is not defined 

for prettydiff.js.

Lib files generate the same error.

**Comment by prettydiff** [comment] 2016-11-23 11:17
This is possibly a duplicate of https://github.com/prettydiff/prettydiff/issues/381

Try running it like this:

* `cd prettydiff` if you aren't in the prettydiff directory
* `node api/node-local.js ` and then tack on your options.

The primary failure here is insufficient documentation.  I will update this shortly as a part of the current patch.

**Comment by prettydiff** [comment] 2016-12-02 23:52
Marking this one as a duplicate of #381

**Closed by prettydiff** 2016-12-02 23:52 UTC
Labels: Defect, Underway
