### ISSUE TITLE
Different results of beautify with wrap option in different prettydiff version

### ISSUE THREAD

**Issue by avishaik** [prettydiff/prettydiff#489] opened 2017-10-17 14:07 UTC
Hello,

We want to use a newer version of prettydiff (version 2.2.8), till now we used version 1.12.18.
When using wrap option 140 on an example XML file, we get two different results with 1.12.18 version and 2.2.8 version

with version 1.12.18 we get 27 lines, and in version 2.2.8 we get 58 lines.

Why is it so?

Thanks.

**Comment by prettydiff** [comment] 2017-10-17 21:38
I cannot say without looking having the code sample to reproduce this behavior.  Guessing it could be there were defects in 1.12.18 as that version is ancient.

**Comment by avizov** [comment] 2017-10-25 12:19
Hello,
I also tried to use wrap option with following xml but without success. It looks that doesn't wrap the xml.
<mvc:view xmlns:core="sap.ui.core" xmlns:mvc="sap.ui.core.mvc" xmlns="sap.m" controllername="sapui5.controller.alex" xmlns:html="http://www.w3.org/1999/xhtml">
    <app>
        <pages>
            <page title="Title">
                <content></content>
            </page>
        </pages>
    </app>
   
    <app>
        <pages>
            <page title="Title"></page>
            <page title="Title"></page>
            <page title="Title"></page>
            <page title="Title"></page>
            <page title="Title"></page>
        </pages>
    </app>

</mvc:view>

with following prettydiff settings: /*prettydiff.com unformatted: true, wrap: "80" */

I would like to emphasize that with old version (1.12.18) it worked as expected.
Is it a bug?

**Comment by prettydiff** [comment] 2017-10-25 16:36
This looks like a valid defect.  I have starting looking at this but don't have any immediate information to share.

**Comment by prettydiff** [comment] 2017-10-26 20:16
Looking at this today.  Some notes:

1. The width option is ignored on tags, applied only to text content, if the option *unformatted* is set to true.  Even still this is defective.
2. The width isn't executing because the attributes have not be injected back into the tag yet and so the tag looks like it is only the tag name and delimiters.  I need to look more to determine why this is the case.

**Comment by yuvalmorad** [comment] 2017-11-13 16:54
Hi,
thanks
in which patch I can test the fix?

**Comment by avishaik** [comment] 2017-11-20 06:24
Hi,
Is there a new patch with the fix?

**Comment by prettydiff** [comment] 2017-11-20 12:06
Not patch yet.  I am currently working on Pretty Diff 3 which is a going to be a huge refresh of the code.  I will analyze this issue in specific detail once I get to it.

**Comment by avishaik** [comment] 2017-11-20 13:01
The fix will be in 2.2.8?

**Comment by yuvalmorad** [comment] 2017-11-23 11:09
Hi,
merging to new major version 3 will be higher effort for us.
will there also be a patch just for 2.2.8?

**Comment by yuvalmorad** [comment] 2017-12-26 08:48
Hi again and happy holiday,
Will there be a patch 2.2.8 just for the attribute format issue?
migration to 3.0 might require more effort
Thanks
Yuval

**Comment by yuvalmorad** [comment] 2018-03-11 17:01
Hi again,
did you stop working on the tool?

**Comment by yuvalmorad** [comment] 2018-03-11 17:07
Hi Austin,
Do you foresee any solution in the near future?
Regards
Yuval

**Comment by prettydiff** [comment] 2018-03-11 22:34
I am still working on it.  Here is my recent progress: https://github.com/prettydiff/prettydiff/commits/3.0.0

**Comment by yuvalmorad** [comment] 2018-03-12 07:44
Hi Austin,
I assume major version release takes time and is complicated
Do you see an option that just the format xml issue for new line per attribute and line wrapping
would be fixed in a separate patch , not major version release?
Regards
Yuval

**Closed** 2018-11-25 11:45 UTC
Labels: Beautification, Defect, Underway
