### ISSUE TITLE
CLI not recognizing .prettydiffrc

### ISSUE THREAD

**Issue by filipesilva** [prettydiff/prettydiff#185] opened 2015-10-14 15:35 UTC
Running CLI commands with arguments seems to work, but the `.prettydiffrc` file doesn't seem to be recognized (help message is always displayed). 

This might be related with me being on windows, via gitbash (which uses mingw).

![image](https://cloud.githubusercontent.com/assets/4172079/10488582/3b395ee2-7291-11e5-8b4a-807552fcf512.png)

**Comment by prettydiff** [comment] 2015-10-14 18:00
There were two defects to blame for this near the bottom of the code:

Before -

                            pdrc = require(pdrcpath);
                            if (pdrc.preset !== undefined) {
                                options.help = false;
                                options = pdrc.preset(options);
                                init();
                            }

After - 

                            pdrc = require(pdrcpath);
                            if (pdrc.preset !== undefined) {
                                help = false;
                                options = pdrc.preset(options);
                                if (s !== options.source) {
                                    pathslash("source", options.source);
                                }
                                if (d !== options.diff) {
                                    pathslash("diff", options.diff);
                                }
                                if (o !== options.output) {
                                    pathslash("output", options.output);
                                }
                                init();
                            }

The defects:

1. Internally I use a reference flag named `help` to determine whether or not to display the documentation to console output.  I was reassigning the `options.help` option instead of the flag.
2. I am evaluating file system paths properly, but not after reading the `.prettydiffrc` file.

The corrected file is available at http://prettydiff.com/api/node-local.js and it will be published to NPM later today.

**Comment by filipesilva** [comment] 2015-10-14 19:10
Nice, I'll try it again tomorrow then. Cheers!

**Comment by filipesilva** [comment] 2015-10-15 13:58
There might be a few issues with yesterday's changes. With this setup:

```
filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/sandbox/prettydiffrctest                  
$ cat .prettydiffrc                                                               
{                                                                                 
        "source": "test",                                                         
        "mode": "beautify",                                                       
        "readmethod": "auto"                                                      
}                                                                                 
                                                                                  
filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/sandbox/prettydiffrctest                  
$ cat test/file.js                                                                
var arr = [1, 2                                                                   
3,                                                                                
4];                                                                               
                                                                                  
        var int = 42;                                                             
                                                                                  
filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/sandbox/prettydiffrctest                  
$ cat package.json                                                                
{                                                                                 
  "name": "prettydiffrctest",                                                     
  "version": "1.0.0",                                                             
  "description": "",                                                              
  "main": "index.js",                                                             
  "scripts": {                                                                    
    "test": "echo \"Error: no test specified\" && exit 1",                        
    "pd": "prettydiff source:'test' mode:'beautify' readmethod:'subdirectory'",   
    "pdrc": "prettydiff"                                                          
  },                                                                              
  "author": "",                                                                   
  "license": "ISC",
  "devDependencies": {
    "prettydiff": "^1.14.8"
  }                                                           
}

filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/sandbox/prettydiffrctest
$ prettydiff version
Version: 1.14.8 Dated: 14 October 2015                                                                               
```

- Can't open help:
```
filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/sandbox/prettydiffrctest
$ node_modules/.bin/prettydiff help:true
Error: 'source' argument is empty

filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/sandbox/prettydiffrctest
$ node_modules/.bin/prettydiff help:"true"
Error: 'source' argument is empty
```

- Can't beautify dir, and have different behavior when running as a npm script vs global/local install

```
filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/sandbox/prettydiffrctest
$ prettydiff source:'test' mode:'beautify' readmethod:'subdirectory'
{ [Error: ENOENT, stat 'C:\Users\filipe.silva\AppData\Roaming\npm\node_modules\prettydiff\api\test']
  errno: -4058,
  code: 'ENOENT',
  path: 'C:\\Users\\filipe.silva\\AppData\\Roaming\\npm\\node_modules\\prettydiff\\api\\test' }

filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/sandbox/prettydiffrctest
$ node_modules/.bin/prettydiff source:'test' mode:'beautify' readmethod:'subdirectory'
{ [Error: ENOENT, stat 'E:\sandbox\prettydiffrctest\node_modules\prettydiff\api\test']
  errno: -4058,
  code: 'ENOENT',
  path: 'E:\\sandbox\\prettydiffrctest\\node_modules\\prettydiff\\api\\test' }

filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/sandbox/prettydiffrctest
$ npm run pd

> prettydiffrctest@1.0.0 pd E:\sandbox\prettydiffrctest
> prettydiff source:'test' mode:'beautify' readmethod:'subdirectory'

Error: 'diff' argument is empty
```

- Can't read .prettydiffrc
```
filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/sandbox/prettydiffrctest
$ prettydiff
Error: 'source' argument is empty

filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/sandbox/prettydiffrctest
$ node_modules/.bin/prettydiff
Error: 'source' argument is empty

filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/sandbox/prettydiffrctest
$ npm run pdrc

> prettydiffrctest@1.0.0 pdrc E:\sandbox\prettydiffrctest
> prettydiff

Error: 'source' argument is empty
```

**Comment by filipesilva** [comment] 2015-10-15 13:58
Do you want me to open new issues for all these?

**Comment by prettydiff** [comment] 2015-10-15 14:19
Not yet. Let me investigate first since there is quite a bit listed.

**Comment by prettydiff** [comment] 2015-10-15 14:50
I made an update at http://prettydiff.com/api/node-local.js

Try overwriting the file of the same name on your drive with the contents above.  If this fixes the listed issues I will publish this immediately.  It did not occur to me until after I went to bed that there were some flags that I set for the default .prettydiffrc format that I did not apply for JSON format.

**Comment by filipesilva** [comment] 2015-10-15 15:03
I overwrote `node-local.js` in the local instalation. And then retried the above scenarios (in order).

- Help is working again with `node_modules/.bin/prettydiff help`
- Dir beautification has the same output as in my previous comment
- `.prettydiffrc` does not seem to be used (but now help is displayed instead)

**Comment by prettydiff** [comment] 2015-10-15 15:07
Thanks, I will continue to investigate

**Comment by filipesilva** [comment] 2015-10-15 15:12
Anything I can do to help meanwhile?

**Comment by filipesilva** [comment] 2015-10-15 15:30
I'm trying to get to the bottom of it as well. In line 1755 of `node-local.js`, this

```
pdrcpath  = __dirname.replace(/((\/|\\)api)$/, "") + "/.prettydiffrc",
```

Should be (I think)

```
pdrcpath  = process.cwd().replace(/((\/|\\)api)$/, "") + "/.prettydiffrc",
```

Otherwise it's looking for the rc file in it's own dir (as opposed to where the script was called from).

**Comment by filipesilva** [comment] 2015-10-15 15:39
Using `path = require('path')`, this will correctly generate the path to the rc file on windows: `path.join(process.cwd().replace(/((\/|\\)api)$/, ""), ".prettydiffrc")`.

**Comment by prettydiff** [comment] 2015-10-15 15:59
Did that one change resolve most of the remaining problems for you?  I made the change from `process.cwd()` to `__dirname` due to a rare edge case.

I discovered that if JavaScript is run from another scripting language or a shell environment based upon another run time `process.cwd()` always evalutes to `/` and then doesn't know where it is called from or how to resolve any relative paths.  Even in this edge case `__dirname` remains valid because it always knows where the file is located at execution time.

I can solve this by only applying `__dirname` if `process.cwd() === "/"`.

**Comment by filipesilva** [comment] 2015-10-15 16:02
No, I'm still tracing the issue around. It seems that right now the rc file is being correctly read, but the path to `source` isn't being correctly computed. Still trying to find out where that happens.

**Comment by filipesilva** [comment] 2015-10-15 16:11
In line 52, the assignment of `cwd = __dirname,` instead of `cwd = process.cwd(),` is causing `absPath` to calculate the path to source based on the location of `node-local.js` instead of the calling location.

Also, the final return of `absPath` can joined as `return path.join(cwd, itempath);`

**Comment by prettydiff** [comment] 2015-10-15 16:13
Here is the quick road map:

At the bottom there is the `args` function, which contains an `fs.stat`.  At the bottom of the `fs.stat` the .prettydiffrc file is evaluated and upon evaluation a function `init()` is called.  `init()` contains a function called `status` to determine whether it should be reading a single file, direct text input, or a directory.  It performs this kind of evaluate against the `options.source` and if available `options.diff` and `options.output`.

If status determines it should be working with a directory it fires the `directory` function, when then fires `readLocalFile` upon each file it resolves in the given directory.  If status determines it should be working directly with a file just goes straight to `readLocalFile` using the actual option value of the provided local file system path.

In the `directory` function some recursive logic and additional flags happen in the case the `readmethod` is `subdirectory` otherwise the same things occur.  Files are identified from the given directory and an object is created representing the given file with the path stored in a property called `absolutepath` in an array called `sfiles` for files originating from the `option.source` or `dfiles` from `option.diff`.  These arrays commonly referred to with the variable `item` as the logic for both is the same.

I just got your previous comment, so you have probably figured all this out.  I am updating line 52 and posting the updated code online in the same location.

**Comment by filipesilva** [comment] 2015-10-15 16:40
Hm... I fixed a couple more path joins, and am now looking at how files are processed after they are listed. Inside `preprocess`, in the else of `if (options.mode === "diff")`, there's `if (options.output !== "")`. As far as I can tell, this evaluates to false, which causes the file to not be processed.

See below for output with a debug message showing the `sfiles` var.

```
filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/sandbox/prettydiffrctest
$ npm run pdrc

> prettydiffrctest@1.0.0 pdrc E:\sandbox\prettydiffrctest
> prettydiff

---------------sfiles is [ 'E:/sandbox/prettydiffrctest/test/file.js' ]

Pretty Diff beautified 0 files. Executed in 0.067 seconds.
```

**Comment by prettydiff** [comment] 2015-10-15 21:48
I just updated the code again.  Continuing to test various scenarios.

**Comment by prettydiff** [comment] 2015-10-16 01:55
If you could try it out again.  I made some additional refinements on my Windows machine to problems that I could not reproduce on my Mac.

http://prettydiff.com/api/node-local.js

**Comment by filipesilva** [comment] 2015-10-16 11:42
I put replaced the file and tested a few commands again (same setup as my first comment here).

```
filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/sandbox/prettydiffrctest
$ node_modules/.bin/prettydiff help

Pretty Diff beautified 0 files. Executed in 0.059 seconds.


filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/sandbox/prettydiffrctest
$ node_modules/.bin/prettydiff

Pretty Diff beautified 0 files. Executed in 0.059 seconds.


filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/sandbox/prettydiffrctest
$ node_modules/.bin/prettydiff source:'test' mode:'beautify' readmethod:'subdirectory'

Pretty Diff beautified 0 files. Executed in 0.01 seconds.


filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/sandbox/prettydiffrctest
$ npm run pd

> prettydiffrctest@1.0.0 pd E:\sandbox\prettydiffrctest
> prettydiff source:'test' mode:'beautify' readmethod:'subdirectory'

source is not a directory or file

filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/sandbox/prettydiffrctest
$ npm run pdrc

> prettydiffrctest@1.0.0 pdrc E:\sandbox\prettydiffrctest
> prettydiff


Pretty Diff beautified 0 files. Executed in 0.06 seconds.
```

I can't see the help menu via `node_modules/.bin/prettydiff help`, which to me means that it must be reading from `.prettydiffrc`. This might be a situation where you'd actually want the help listing to be shown and not do anything else, but that is beside the scope of this issue.

There might be a problem in the file listing still. Also, the result of `npm run pd` surprised me a bit, I expected it to be the exact same as the one above it.

I'll try to make it work using your code as base, and send a PR if I'm able to. The changes you showed me on http://prettydiff.com/api/node-local.js, are those on a branch in the repo?

**Comment by filipesilva** [comment] 2015-10-16 13:03
I assumed that when no output was provided, files would be outputted to the same directory. Now I see that is not so by design, which was what caused the `Pretty Diff beautified 0 files` bit up there. My `.prettydiffrc` now looks like this (output added):

```
{
	"source": "test",
	"output": "test",
	"mode": "beautify",
	"readmethod": "auto"
}

```

After this I found a couple of paths in `preprocess` that were being mistakenly joined (`group + filename` that returned stuff like `E:\sandbox\prettydiffrctest\testE:\sandbox\prettydiffrctest\test\file.js`).

After fixing those, it seems reports were also to be affected by this:

```
filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/sandbox/prettydiffrctest
$ npm run pdrc

> prettydiffrctest@1.0.0 pdrc E:\sandbox\prettydiffrctest
> prettydiff

here -report.html
here

Pretty Diff beautified 1 file. Executed in 0.097 seconds.


Error writing report output.

{ [Error: ENOENT, open 'E:\sandbox\prettydiffrctest\testE:\sandbox\prettydiffrctest\test\file.js-report.html']
  errno: -4058,
  code: 'ENOENT',
  path: 'E:\\sandbox\\prettydiffrctest\\testE:\\sandbox\\prettydiffrctest\\test\\file.js-report.html' }

Error writing report output.

{ [Error: ENOENT, open 'E:\sandbox\prettydiffrctest\testE:\sandbox\prettydiffrctest\test\file.js']
  errno: -4058,
  code: 'ENOENT',
  path: 'E:\\sandbox\\prettydiffrctest\\testE:\\sandbox\\prettydiffrctest\\test\\file.js' }
```

Looking at `fileWrite` I see in a few places things like `address.oabspath + finalpath`, which seems to be the problem since `finalpath` holds the full path in this execution. However, this bit of code inside `fileWrite`

```
            if (options.mode === "diff") {
                finalpath    = (dirs.length > 0)
                    ? "__" + dirs.join("__") + "__" + filename
                    : filename;
                options.diff = dfiledump[data.index];
            } else {
                finalpath = (method === "file")
                    ? filename
                    : dirs.join("/") + "/" + filename;
            }
```

Seems to mean that finalpath might be either a path or a filename. I set it to be the non-filename branch always, remove the `address.oabspath +` bits, and run two simple tests that seem to pass, with these rc files:

```
{
	"source": "test",
	"output": "test",
	"mode": "beautify",
	"readmethod": "auto"
}
```

and
```
{
	"source": "test/file.js",
	"diff": "test/file.js",
	"mode": "diff",
	"readmethod": "auto"
}
```

It seems to be working, but I am worried that fiddling with the `finalpath` generation might have broken scenarios that I don't know about. Your changes plus mine are included in the PR I'm submitting now.

**Closed** 2015-10-30 04:34 UTC
Labels: Defect, Underway
