### ISSUE TITLE
Doesn't indent @keyframes correctly in SCSS 

### ISSUE THREAD

**Issue by najela** [prettydiff/prettydiff#136] opened 2015-08-07 20:22 UTC
Hello

```scss
@keyframes infinite-spinning {
  from {
    transform: rotate(0deg);
  }
  to {
    transform: rotate(360deg);
  }
}
```

Gets beautified to

```css
@keyframes infinite-spinning {
    from {
        transform: rotate(0deg);
    }

to {
        transform: rotate(360deg);
    }
}
```

I am using [atom beautify](https://github.com/Glavin001/atom-beautify).

> CC https://github.com/Glavin001/atom-beautify/issues/500

**Comment by prettydiff** [comment] 2015-08-07 23:27
I cannot reproduce the problem.  Go to http://prettydiff.com/?m=beautify

When I try it the code is auto-detected as `LESS` language, but the output is still correct.

**Comment by ArekSredzki** [comment] 2015-08-13 05:51
This should be fixed in #142

**Comment by prettydiff** [comment] 2015-08-13 13:42
The error is evident when using the cssinsertlines option.  I can reproduce now.  Examining the pull request.

**Comment by ArekSredzki** [comment] 2015-08-16 01:10
Can confirm, this has now been resolved.

**Closed** 2015-08-18 03:47 UTC
Labels: Defect, QA
