### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by johnnydulicious** [prettydiff/prettydiff#425] opened 2017-03-30 18:45 UTC
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

RangeError: Maximum call stack size exceeded
Merge remote-tracking branch 'upstream/master'
    at safeSort__ascend_recurse (/Users/jon.duay/repos/forks/newproject/node_modules/prettydiff/lib/safeSort.js:123:60)
    at safeSort__ascend_recurse (/Users/jon.duay/repos/forks/newproject/node_modules/prettydiff/lib/safeSort.js:153:25)
    at safeSort__ascend_recurse (/Users/jon.duay/repos/forks/newproject/node_modules/prettydiff/lib/safeSort.js:153:25)

Issue occurred while prettifying 2.1MB XML file into a 3.3 MB XML file.

**Comment by johnnydulicious** [comment] 2017-03-30 18:47
Was able to fix this locally by wrapping setTimeout on extdef() in line 153:

`if (c < len) {
                        setTimeout(function() { // fixing maximum call stack size exceeded
                            extref();
                        }, 0);// end fixing maximum call stack size exceeded
                    } else {`

**Comment by prettydiff** [comment] 2017-03-30 22:53
Were you executing this from the command line or browser?  I will look into an alternate approach.

**Comment by johnnydulicious** [comment] 2017-03-30 23:16
This was from the command line, via GulpPrettydiff. We were using prettydiff as part of a batch processing script to generate XML content from JSON and YAML models.

**Comment by prettydiff** [comment] 2017-03-31 01:37
Founds some big data to experiment: ftp://ftp.nlm.nih.gov/nlmdata/.catpluslease/catplus.20170101.xml

**Comment by prettydiff** [comment] 2017-03-31 01:53
Firefox and Chrome can handle 19mb XML, though these operations just about killed my Macbook Pro.  I have 64gb memory on my windows box, so I will try from the command line on there in a bit.

**Comment by prettydiff** [comment] 2017-03-31 01:55
About how long does this operation take before the error occurs?  The completed operation took about 19 seconds in the browsers.  If this fails for you almost immediately then the issue could be something like an endless loop (bad logic) opposed to a large file that crushes your memory.

Also, how much RAM do you have on the machine where this error occurred?

**Comment by johnnydulicious** [comment] 2017-03-31 02:02
16gb RAM on my MBP. The error occured around 3s into the operation. The source JSON had quite a lot of child objects nested within objects, so the recursive nature of the object schema may have also caused this.

**Comment by prettydiff** [comment] 2017-04-02 00:58
I just tried to beautify a 118mb file on my windows box from CLI and it does crash, but the error looks like this:

```
c:\Users\austincheney\prettydiff>node api\node-local.js mode:"beautify" source:"..\catplus1.xml" readmethod:"filescreen"

<--- Last few GCs --->

[3972:000001FE2D0BE9F0]    45417 ms: Mark-sweep 1387.4 (1426.9) -> 1386.8 (1426.9) MB, 480.9 / 0.0 ms  allocation failure GC in old space requested
[3972:000001FE2D0BE9F0]    45893 ms: Mark-sweep 1386.8 (1426.9) -> 1386.8 (1395.9) MB, 475.7 / 0.0 ms  last resort gc
[3972:000001FE2D0BE9F0]    46354 ms: Mark-sweep 1386.8 (1395.9) -> 1386.8 (1395.9) MB, 461.3 / 0.0 ms  last resort gc


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000001AD032C0D59 <JS Object>
    2: markuppretty__tokenize_tag(aka markuppretty__tokenize_tag) [c:\Users\austincheney\prettydiff\lib\markuppretty.js:~447] [pc=00000065F934CFF6](this=000001AD03204311 <undefined>,end=000001AD03204471 <String[0]: >)
    3: markuppretty__tokenize(aka markuppretty__tokenize) [c:\Users\austincheney\prettydiff\lib\markuppretty.js:~228] [pc=00000065F9352510](this=000001AD03204311 <undefined>)
  ...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```

I am thinking the reported defect is related to a given instance of XML.  I get that same error message when running the big file through the old 1.16.37 version used from Node as well as the current version.  Is there any chance you could post that XML file into a gist so that I could continue testing?

**Comment by prettydiff** [comment] 2017-05-17 22:44
While the defect is valid I cannot reproduce it, so I will close this issue for now.

**Closed by prettydiff** 2017-05-17 22:44 UTC
Labels: Defect, Not started, Parsing, Requested Additional Information
