### ISSUE TITLE
Markup tag with document type not closed get prettyDiff stuck when beautify

### ISSUE THREAD

**Issue by kaizer200** [prettydiff/prettydiff#76] opened 2015-04-15 11:42 UTC
steps to reproduce:
1) write the following xml:
\<!DOCTYPE html>
\<person att3="3">\<\person>
2) click beautify - works ok
3)remove the closing '>' sign from the first line
4) prettyDiff editor / browser get stuck (long running script problem...)

**Comment by prettydiff** [comment] 2015-04-15 17:19
I believe this issue is a duplicate of issue #75.  Please feel free to reopen if I am wrong.

**Closed by prettydiff** 2015-04-15 17:19 UTC
Labels: Defect, Underway

**Comment by kaizer200** [comment] 2015-04-15 19:25
tested OK
